Add instructions to set up local environment
code-for-venezuela/c4v-py pull request #44
Opened 2020-10-25 21:10 UTC by marianelamin

I added some instructions that illustrate how to set up the local environment so any new member can follow steps and get ready to start collaborating.

Please review, add, remove, comment.
Feedback is greatly appreciated.

@Edilmo @dieko95

2020-10-26 10:07 UTC, dieko95 requested changes

2020-10-26 10:07 UTC, dieko95 commented on README.md
> +4. Navegate to the folder `cd c4v-py`
There's a typo 🙈

2020-10-31 17:47 UTC, Edilmo approved these changes
LGTM (just the fun typo :) )

2020-11-01 00:55 UTC, marianelamin commented on README.md
> +4. Navegate to the folder `cd c4v-py`
Good catch! Thanks!

2020-11-03 20:45 UTC, dieko95 approved these changes

2020-11-04 04:05 UTC, merged