Luis/ci config
code-for-venezuela/c4v-py pull request #82
Opened 2021-07-08 19:27 UTC by LDiazN

# Workflow to publish a new version

We need to automate the publishing of a new version to PYPI whenever we push changes to master

## Proposed solution
Create a new workflow that will trigger whenever a push to master is done, and publish our library to PYPI using `poetry publish` command. Add a string with current datetime to version as a suffix, so it is different whenever we publish a new one.

## Relevant files:
* `.github/update_dev_version.py` - Script to set up new version to use when publishing the library
* `.github/workflows/release_package.yml` - Workflow itself to publish this library

2021-07-09 18:25 UTC, dieko95 requested changes

2021-07-09 19:16 UTC, LDiazN commented on .github/update_dev_version.py
> +    sys.stdout.write(line)
Changed 👍

2021-07-09 19:20 UTC, dieko95 approved these changes
LGTM 👍 🚀

2021-07-13 00:16 UTC, Edilmo approved these changes
LGTM

2021-07-15 20:55 UTC, merged